@baseUrl = http://localhost:3001


### Todos os produtos
GET {{baseUrl}}/products

### Por nome
GET {{baseUrl}}/products?name=Monitor

### Por preço mínimo
GET {{baseUrl}}/products?minPrice=500

### Por preço máximo
GET {{baseUrl}}/products?maxPrice=1500

### Combinando filtros
GET {{baseUrl}}/products?name=Monitor&minPrice=500&maxPrice=1500
### Cadastrar produto

POST {{baseUrl}}/products
Content-Type: application/json

{
    "name":"monitor",
    "price":1100,
    "stock":10
}

### Atualizar produto
PATCH {{baseUrl}}/products/6ac27df7898a29d12d35742e
Content-Type: application/json

{
  "price": 1000
}



### Deletar produto
DELETE {{baseUrl}}/products/6ac27df7898a29d12d35742e